export const authErrors = new Map(
  Object.entries({
    "admin-restricted-operation": "Giới hạn cho quản trị viên.",
    "app-not-authorized":
      "Ứng dụng không được phép sử dụng Firebase Authentication.",
    "app-not-installed": "Ứng dụng không được cài trên thiết bị này.",
    "captcha-check-failed": "Mã reCAPTCHA không hợp lệ.",
    "code-expired": "Mã SMS đã hết hạn.",
    "cordova-not-ready": "Cordova chưa sẵn sàng.",
    "cors-unsupported": "Trình duyệt không hỗ trợ.",
    "credential-already-in-use": "Thông tin xác thực đã được sử dụng.",
    "custom-token-mismatch": "Mã thông báo không khớp.",
    "requires-recent-login": "Yêu cầu xác thực gần đây.",
    "dynamic-link-not-activated":
      "Kích hoạt Dynamic Links trong Firebase Console.",
    "email-already-in-use": "Email đã được sử dụng.",
    "expired-action-code": "Mã hành động đã hết hạn.",
    "cancelled-popup-request": "Thao tác bị hủy do popup khác.",
    "internal-error": "Lỗi nội bộ.",
    "invalid-app-credential": "Trình xác thực ứng dụng không hợp lệ.",
    "invalid-app-id": "ID ứng dụng không hợp lệ.",
    "invalid-user-token": "Thông tin xác thực người dùng không hợp lệ.",
    "invalid-verification-code": "Mã xác minh không hợp lệ.",
    "invalid-email": "Email không hợp lệ.",
    "invalid-api-key": "Khóa API không hợp lệ.",
    "invalid-credential": "Thông tin xác thực không hợp lệ.",
    "invalid-persistence-type": "Loại lưu trữ không hợp lệ.",
    "invalid-phone-number": "Số điện thoại không hợp lệ.",
    "invalid-provider-id": "ID nhà cung cấp không hợp lệ.",
    "invalid-action-code": "Mã hành động không hợp lệ.",
    "wrong-password": "Mật khẩu không hợp lệ.",
    "auth-domain-config-required":
      "Bao gồm authDomain khi gọi firebase.initializeApp().",
    "missing-app-credential": "Thiếu xác nhận trình xác thực ứng dụng.",
    "missing-verification-code": "Thiếu mã xác minh SMS.",
    "app-deleted": "FirebaseApp đã bị xóa.",
    "account-exists-with-different-credential":
      "Tài khoản đã tồn tại với thông tin khác.",
    "network-request-failed": "Lỗi mạng.",
    "operation-not-allowed": "Nhà cung cấp đăng nhập bị vô hiệu hóa.",
    "popup-blocked": "Popup bị trình duyệt chặn.",
    "popup-closed-by-user": "Popup đã bị đóng.",
    "provider-already-linked": "Nhà cung cấp đã được liên kết.",
    "quota-exceeded": "Vượt quá hạn mức.",
    "redirect-operation-pending": "Đăng nhập chuyển hướng đang chờ xử lý.",
    "second-factor-already-in-use": "Yếu tố thứ hai đã được đăng ký.",
    timeout: "Thao tác đã hết thời gian chờ.",
    "user-token-expired": "Thông tin xác thực đã hết hạn.",
    "too-many-requests": "Quá nhiều yêu cầu từ thiết bị này.",
    "user-not-found": "Người dùng không tồn tại.",
    "user-disabled": "Tài khoản bị vô hiệu hóa.",
    "user-mismatch": "Thông tin xác thực không khớp.",
    "weak-password": "Mật khẩu yếu.",
    "web-storage-unsupported": "Trình duyệt không hỗ trợ.",
  })
);
